import {
	Contenedor,
	Tabla,
	TablaCabezera,
	TablaCabezeraColumna,
	TablaCabezeraColumnaItem,
	TablaCuerpo,
	TablaCuerpoColumna,
	TablaCuerpoColumnaItem,
} from '../StyledTabla';

export const TablaMovimientos = () => {
	return (
		<Contenedor>
			<Tabla>
				<TablaCabezera>
					<TablaCabezeraColumna>
						<TablaCabezeraColumnaItem>NO.</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							FECHA
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							USUARIO
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							WALLET
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							MOVIMIENTO
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							VALOR
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							HASH. TX
						</TablaCabezeraColumnaItem>
					</TablaCabezeraColumna>
				</TablaCabezera>
				<TablaCuerpo>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>01</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>02</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>VENTA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>03</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>04</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>VENTA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>05</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>06</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>VENTA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>07</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>08</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>VENTA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>09</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>10</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>VENTA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>12</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>COMPRA</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>100USD</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
				</TablaCuerpo>
			</Tabla>
		</Contenedor>
	);
};
