import {
	Contenedor,
	Tabla,
	TablaCabezera,
	TablaCabezeraColumna,
	TablaCabezeraColumnaItem,
	TablaCuerpo,
	TablaCuerpoColumna,
	TablaCuerpoColumnaItem,
} from '../StyledTabla';

export const TablaReferidos = () => {
	return (
		<Contenedor>
			<Tabla>
				<TablaCabezera>
					<TablaCabezeraColumna>
						<TablaCabezeraColumnaItem>
							USUARIO
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							WALLET
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							VENTAS
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							COMISIONES
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							VOL.VENTAS
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							REFERIDOS
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem></TablaCabezeraColumnaItem>
					</TablaCabezeraColumna>
				</TablaCabezera>
				<TablaCuerpo>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCabezeraColumnaItem>
							USERNAME
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							0X08...4786
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							SPONSOR12
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							50 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							100 USD
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>250</TablaCabezeraColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
				</TablaCuerpo>
			</Tabla>
		</Contenedor>
	);
};
