import {
	Contenedor,
	Tabla,
	TablaCabezera,
	TablaCabezeraColumna,
	TablaCabezeraColumnaItem,
	TablaCuerpo,
	TablaCuerpoColumna,
	TablaCuerpoColumnaItem,
} from './StyledTabla';

export const TablaInformativa = () => {
	return (
		<Contenedor>
			<Tabla>
				<TablaCabezera>
					<TablaCabezeraColumna>
						<TablaCabezeraColumnaItem>
							FECHA
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							WALLET
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							USUARIO
						</TablaCabezeraColumnaItem>
						<TablaCabezeraColumnaItem>
							HASH. TX
						</TablaCabezeraColumnaItem>
					</TablaCabezeraColumna>
				</TablaCabezera>
				<TablaCuerpo>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
					<TablaCuerpoColumna>
						<TablaCuerpoColumnaItem>
							01/12/22
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							0X08...4786
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>
							USERNAME
						</TablaCuerpoColumnaItem>
						<TablaCuerpoColumnaItem>OJO</TablaCuerpoColumnaItem>
					</TablaCuerpoColumna>
				</TablaCuerpo>
			</Tabla>
		</Contenedor>
	);
};
